### ISSUE TITLE
Push Lockout

### ISSUE THREAD

**Issue by michaelwisely** [tymorrow/assigner#5]
Students are granted... `developer` access... when we make their repo. I think we can lock them out by changing their access level to `reporter`. They'd be able to pull, but they couldn't push.

Then we could unlock them, I guess. If we're feeling nice.

Links:

* [Access Level codes](http://doc.gitlab.com/ce/api/groups.html#group-members)
* [Edit project team member endpoint](http://doc.gitlab.com/ce/api/projects.html#edit-project-team-member)

**Comment by LinuxMercedes** [comment]
Implemented in 9a821e7
